title: Faizal Edrus Portfolio
description: Faizal Edrus skills, certifications, projects, and learning journey as a cybersecurity professional
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
