title: Faizal Edrus of Cybersecurity Projects
description: To showcases my skills, certifications, projects, and learning journey as a cybersecurity professional
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
